name: Run Testing Automation on Deployment with slack notification

on:
  deployment:
    types: [deployment]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  test_and_notify:
    name: Build Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install mocha

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
   
      - name: Run tests
        run: npm run test:all

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # Notify test results in Slack
      - name: Notify Slack
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": "Test Results",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "A build is deployed into ${{ github.repository }} :tada:\n*${{ github.event.pull_request.user.login }}* has just contributed to ${{ github.repository }} :partying_face:"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
